# INSTALAR NUMPY

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np

# Como crear un Array

In [49]:
my_list = (0, 1, 2, 3, 4)

my_array = np.array(my_list)

In [50]:
print(type(my_array))

<class 'numpy.ndarray'>


In [11]:
np.arange(start=2, stop=10, step=2)

array([2, 4, 6, 8])

In [12]:
np.full(shape=(2,2), fill_value=5)

array([[5, 5],
       [5, 5]])

In [13]:
base = np.linspace(2, 4, 6)
base

array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [14]:
np.pi

3.141592653589793

In [15]:
my_array = np.full_like(base, np.pi)
my_array

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265])

# crear arrays aleatorios

In [16]:
# se usa la funcion rand.
np.random.rand(2,2)

array([[0.1651497 , 0.80931733],
       [0.55949637, 0.13401175]])

In [17]:
np.random.uniform(low=0, high=1, size=6)

array([0.15831828, 0.62969773, 0.25939288, 0.40199468, 0.27033362,
       0.13005329])

In [18]:
#como distribucion estandar.
np.random.rand(2,2)

array([[0.16602864, 0.29152094],
       [0.42695171, 0.79067128]])

In [19]:
#con distribucion normal. (la visualizacion es acampanada)
np.random.normal(loc=0, scale=2, size=6)

array([ 2.81947005, -0.25122492, -1.59000075, -2.07231884,  2.50643489,
        0.0257591 ])

# Tamaños de arrays

In [22]:
# se usa para generar valores 
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [24]:
b = np.reshape(a,[3,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
#todos los elementos dentro del array se consideran del mismo dato
print(b.dtype) 

int32


In [26]:
#aplana los datos.
c = b.flatten()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing con Arrays

In [28]:
#Manipulacion de Arrays
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
matriz =np.arange(9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
#ingresando fila uno y columna 2
print(matriz[1,2])


5


In [33]:
#Obtener todos los elementos de la fila 0
print(matriz[0, :])

[0 1 2]


In [34]:
#Todos los elementos apartir de la columna 1
print(matriz[:, 1])

[1 4 7]


In [36]:
#Tobteber el primer y 2 elemento de la columna 1 y 2
print(matriz[0:2, 0:2])


[[0 1]
 [3 4]]


In [37]:
# Obtener todo
print(matriz[:,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Copiar Arrays (para no sobre escribir lo que ya estamos trabajando para luego poder reutilizarlo por si el codigo se rompe).

In [38]:
a = np.array([2, 4, 6])
a

array([2, 4, 6])

In [39]:
b = a.copy()
print(b)

[2 4 6]


In [40]:
a[1] = 8
print(a) #rremplaza el valor 1 por el 8

[2 8 6]


In [41]:
print(b)

[2 4 6]


In [42]:
a1 = np.array([2,4,6])
a1

array([2, 4, 6])

In [43]:
b1 = a1
print(b1)

[2 4 6]


In [47]:
a1[1] = 8
print(a1)

[2 8 6]


In [48]:
print(b1)

[2 8 6]


# Operaciones basicas con Arrays

In [51]:
#SUMA
a = np.arange(5,11)
a

array([ 5,  6,  7,  8,  9, 10])

In [52]:
#le suma 10 a cada elemento
print(a+10)


[15 16 17 18 19 20]


In [56]:
#RESTA
print(a-10)

[-5 -4 -3 -2 -1  0]


In [58]:
#restas entre arrays
b = np.full(4,3)
c = np.ones(4, dtype ='int')

In [59]:
print(b - c)

[2 2 2 2]


In [60]:
#Multiplicacion entre arrays
a = np.array([[2,3],[2,3],[2,3]])
a.shape

(3, 2)

In [66]:
b = np.array([[1,6,5,2,7],[1,2,7,0,9]])
b.shape

(2, 5)

In [65]:
np.matmul(a,b)

array([[ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41]])

In [69]:
#traspuesta de la matriz
c.T

array([1, 1, 1, 1])

## estadisticas.

In [71]:
lista = [74,74,72,72,73,69,69,71,73,73,74,74,69,70,73,75,]

In [72]:
np.mean(lista)

72.1875

In [76]:
lista.sort()

In [77]:
print(lista)

[69, 69, 69, 70, 71, 72, 72, 73, 73, 73, 73, 74, 74, 74, 74, 75]


In [79]:
np.std(lista)

1.9435389756832766

In [80]:
np.min(lista)

69

# Mascaras

In [82]:
a = np.arange(0,20).reshape(2,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [84]:
#Busca los valores pares.
mascara = ((a % 2)==0)

In [85]:
print(mascara)

[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]


In [86]:
#Devuelve los valores pares en numeros
a[mascara]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
b 

array([[1, 6, 5, 2, 7],
       [1, 2, 7, 0, 9]])